name: dynamic_cached_fonts
description: A font loader to download, cache and load web fonts in flutter with support for Firebase Cloud Storage.
version: 1.0.0
repository: https://github.com/sidrao2006/dynamic_cached_fonts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.0.8
  flutter_cache_manager: ^3.1.2
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/GoogleService-Info.plist
  - /example/macos/GoogleService-Info.plist
  - /example/web/index.html
