name: dynamic_cached_fonts
description: A font loader to download, cache and load web fonts in flutter with support for Firebase Cloud Storage.
version: 2.0.0-dev.0
repository: https://github.com/sidrao2006/dynamic_cached_fonts

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ">=8.0.0 <13.0.0"
  flutter_cache_manager: ^3.1.2
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/GoogleService-Info.plist
  - /example/macos/GoogleService-Info.plist
  - /example/web/index.html
  - /example/lib/firebase_options.dart
